cc_library(
  name = "poller",
  srcs = ["poller.cpp"],
  hdrs = ["poller.h"],
  visibility = ["//visibility:public"],
  # deps = [
  #   "@com_github_grpc_grpc//:grpc++",
  #    "//:storage_cc_grpc"
  # ]
)